version: '3'

services:
  web:
    image: fastapi_base_image
    build: ./src
    restart: always
    volumes:
      - ./src:/app
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8003
    ports:
      - 8003:8001
    network_mode: host
    container_name: fastapi_base